<<<<<<< HEAD
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "systemstoolkit"
description = "Helper functions for Systems ToolKit (STK)"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT License"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
]
dependencies = [
    "numpy",
    "dateutils",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "systemstoolkit.__version__"}

[project.urls]
"Homepage" = "https://github.com/jolsten/systemstoolkit"
=======
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "systemstoolkit"
description = "Helper functions for Systems ToolKit (STK)"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT License"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
]
dependencies = [
    "numpy",
    "dateutils",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "systemstoolkit.__version__"}

[project.urls]
"Homepage" = "https://github.com/jolsten/systemstoolkit"
>>>>>>> 35a54389bd7199e199d4593870c92d2e6095ccf4
